---
- name: Issue show commands
  hosts: sandbox
  connection: local
  tasks:
    - name: Show ip int brief
      ios_commmand:
        commands:
        - show ip int brief
      provider:
        host: iox-xe-mgmt-latest.cisco.com
        port: 8181
        authorize: yes
        username: root
        password: Cisco12345
      register: if_data

    - name: Interfaces output
      debug:
        var: if_data['stdout_line'][0]
